apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../sources/grafana-community-loki.yaml
  - ../../sources/grafana.yaml
  - rbac.yaml
  - helmrelease.yaml
  - datasource.yaml
  - netpol-loki.yaml
